package az.siftoshka.habitube.presentation.screens.discover.items

import androidx.annotation.StringRes
import az.siftoshka.habitube.R
import az.siftoshka.habitube.presentation.screens.discover.DiscoverScreen

/**
 * Item for [DiscoverScreen].
 */
class DiscoverGenresItem(
    val category: DiscoverGenresCategory,
    @StringRes var text: Int
)

enum class DiscoverGenresCategory(val id: String) {
    ACTION("28"),
    ADVENTURE("12"),
    ANIMATION("16"),
    COMEDY("35"),
    CRIME("80"),
    DOCUMENTARY("99"),
    DRAMA("18"),
    FAMILY("10751"),
    FANTASY("14"),
    HISTORY("36"),
    HORROR("27"),
    MUSIC("10402"),
    MYSTERY("9648"),
    ROMANCE("10749"),
    SCIFI("878"),
    TV_MOVIE("10770"),
    THRILLER("53"),
    WAR("10752"),
    WESTERN("37"),
    ACT_ADV("10759"),
    KIDS("10762"),
    NEWS("10763"),
    REALITY("10764"),
    SCIFI_FANTASY("10765"),
    SOAP("10766"),
    TALK("10767"),
    WAR_POLITICS("10768")
}

val genres = mutableListOf(
    DiscoverGenresItem(
        DiscoverGenresCategory.ACTION,
        R.string.text_genres_action
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.ADVENTURE,
        R.string.text_genres_adventure
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.ANIMATION,
        R.string.text_genres_animation
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.COMEDY,
        R.string.text_genres_comedy
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.CRIME,
        R.string.text_genres_crime
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.DOCUMENTARY,
        R.string.text_genres_documentary
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.DRAMA,
        R.string.text_genres_drama
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.FAMILY,
        R.string.text_genres_family
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.FANTASY,
        R.string.text_genres_fantasy
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.HISTORY,
        R.string.text_genres_history
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.HORROR,
        R.string.text_genres_horror
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.MUSIC,
        R.string.text_genres_music
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.MYSTERY,
        R.string.text_genres_mystery
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.ROMANCE,
        R.string.text_genres_romance
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.SCIFI,
        R.string.text_genres_scifi
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.TV_MOVIE,
        R.string.text_genres_tv_movie
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.THRILLER,
        R.string.text_genres_thriller
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.WAR,
        R.string.text_genres_war
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.WESTERN,
        R.string.text_genres_western
    )
)

val showGenres = mutableListOf(
    DiscoverGenresItem(
        DiscoverGenresCategory.ACT_ADV,
        R.string.text_genres_action_adventure
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.ANIMATION,
        R.string.text_genres_animation
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.COMEDY,
        R.string.text_genres_comedy
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.CRIME,
        R.string.text_genres_crime
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.DOCUMENTARY,
        R.string.text_genres_documentary
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.DRAMA,
        R.string.text_genres_drama
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.FAMILY,
        R.string.text_genres_family
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.KIDS,
        R.string.text_genres_kids
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.MYSTERY,
        R.string.text_genres_mystery
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.NEWS,
        R.string.text_genres_news
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.REALITY,
        R.string.text_genres_reality
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.SCIFI_FANTASY,
        R.string.text_genres_scifi_fantasy
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.SOAP,
        R.string.text_genres_soap
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.TALK,
        R.string.text_genres_talk
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.WAR_POLITICS,
        R.string.text_genres_war_politics
    ),
    DiscoverGenresItem(
        DiscoverGenresCategory.WESTERN,
        R.string.text_genres_western
    )
)